language: go
sudo: false

go:
  - 1.12.x

before_install:
  - sudo apt-get -y install libopus-dev libopusfile-dev libpulse-dev
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make build
  - make check
